# Shared aliases for zsh and bash.

alias g='git'
alias ga='git add'
alias gap='git add --patch'
alias gb='git branch'
alias gba='git branch --all'
alias gbc='git branch --show-current'
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gc='git commit -v'
alias gca='git commit -v --amend'
alias gcb='git checkout -b'
alias gco='git checkout'
alias gd='git diff'
alias gds='git diff --cached'
alias gf='git fetch --prune'
alias glo='git log --oneline --decorate'
alias gloga='git log --oneline --decorate --graph --all'
alias gp='git push'
alias gpl='git pull --ff-only'
alias gr='git remote -v'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbi='git rebase --interactive --autosquash'
alias gs='git status --short --branch --untracked-files'
alias gst='git stash'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gw='git worktree'
alias gwa='git worktree add'
alias gwd='git worktree remove'
alias gwl='git worktree list'

alias ll='ls -alhF'
alias la='ls -ah'
alias l='ls -CF'

alias e='emacsclient -t'
alias ec='emacsclient -c -a emacs'

